nc/urls.py
from django.conf.urls import url

from . import views

app_name = 'nc'
urlpatterns = [
    # User profile
    url(r'^profile/$', views.UserRedirectView.as_view(), name='user-redirect'),
    url(r'^profile/settings/$', views.UserSettingsRedirectView.as_view(), name='user-settings-redirect'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/$', views.UserDetailView.as_view(), name='user-detail'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/update/$', views.UserUpdateView.as_view(), name='user-update'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/settings/update/$', views.UserSettingsUpdateView.as_view(), name='user-settings-update'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/follow/$', views.UserFollowUpdateView.as_view(), name='user-follow'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/follow/request/update/$', views.UserFollowRequestUpdateView.as_view(), name='user-follow-request-update'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/follow/request/delete/$', views.UserFollowRequestDeleteView.as_view(), name='user-follow-request-delete'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/followers/$', views.UserFollowerListView.as_view(), name='user-follower-list'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/following/$', views.UserFollowingListView.as_view(), name='user-following-list'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/portfolio/data/$', views.UserPortfolioDataListView.as_view(), name='user-portfolio-data-list'),

    # Associated Stellar account
    url(r'^account/create/$', views.AccountCreateView.as_view(), name='account-create'),
    url(r'^account/fund/request/create/$', views.AccountFundRequestCreateView.as_view(), name='account-fund-request-create'),
    url(r'^account/(?P<slug>[\w.@+-]+)/update/$', views.AccountUpdateView.as_view(), name='account-update'),
    url(r'^account/(?P<slug>[\w.@+-]+)/delete/$', views.AccountDeleteView.as_view(), name='account-delete'),
    url(r'^account/(?P<slug>[\w.@+-]+)/operation/$', views.AccountOperationListView.as_view(), name='account-operation-list'),

    # Assets
    url(r'^asset/$', views.AssetRedirectView.as_view(), name='asset-redirect'),
    url(r'^trade/$', views.AssetRedirectView.as_view(), name='trade-redirect'),
    url(r'^asset/top/$', views.AssetTopListView.as_view(), name='asset-top-list'),
    # TODO: asset-list
    url(r'^asset/(?P<slug>[\w.@+-]+)/$', views.AssetDetailView.as_view(), name='asset-detail'),
    url(r'^asset/(?P<slug>[\w.@+-]+)/update/$', views.AssetUpdateView.as_view(), name='asset-update'),
    url(r'^asset/(?P<slug>[\w.@+-]+)/trust/$', views.AssetTrustListView.as_view(), name='asset-trust-list'),
    url(r'^asset/(?P<slug>[\w.@+-]+)/trusting/$', views.AssetTrustedByListView.as_view(), name='asset-trusted-by-list'),
    url(r'^asset/exchange/ticker/$', views.AssetExchangeTickerListView.as_view(), name='asset-exchange-ticker'),

    # Leaderboard
    url(r'^leaderboard/$', views.LeaderboardRedirectView.as_view(), name='leaderboard-redirect'),
    url(r'^leaderboard/top/$', views.LeaderboardListView.as_view(), name='leaderboard-list'),

    # Feed
    url(r'^feed/$', views.FeedRedirectView.as_view(), name='feed-redirect'),
    url(r'^feed/news/$', views.FeedNewsListView.as_view(), name='feed-news'),
    url(r'^feed/activity/$', views.FeedActivityListView.as_view(), name='feed-activity'),
    url(r'^feed/activity/create/$', views.FeedActivityCreateView.as_view(), name='feed-activity-create'),

    # Send
    url(r'^send/$', views.SendRedirectView.as_view(), name='send-redirect'),
    url(r'^send/payment/$', views.SendDetailView.as_view(), name='send-detail'),

    # Receive
    url(r'^receive/$', views.ReceiveRedirectView.as_view(), name='receive-redirect'),
    url(r'^receive/payment/$', views.ReceiveDetailView.as_view(), name='receive-detail'),

    # Activity
    # TODO: url(r'^activity/create/$', views.ActivityCreateView.as_view(), name='activity-create'),

    # Performance
    url(r'^performance/create/$', views.PerformanceCreateView.as_view(), name='performance-create'),
    url(r'^toml/update/$', views.AssetTomlUpdateView.as_view(), name='toml-update'),
]

nucleo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

from nc import views as nc_views

urlpatterns = [
    # Web urls
    url(r'^$', nc_views.HomeView.as_view(), name='home'),
    url(r'^', include('nc.urls')),
    url(r'^%s' % settings.ADMIN_PATH, admin.site.urls),

    ## Allauth
    ### Override of account_signup, account_change_password and additional signup flow
    url(r'^accounts/signup/$', nc_views.SignupView.as_view(), name='account_signup'),
    url(r'^accounts/password/change/$', nc_views.PasswordChangeView.as_view(), name='account_change_password'),
    url(r'^accounts/signup/stellar/update/$', nc_views.SignupStellarUpdateView.as_view(), name='account-signup-stellar-update'),
    url(r'^accounts/signup/profile/update/$', nc_views.SignupUserUpdateView.as_view(), name='account-signup-user-update'),
    url(r'^accounts/signup/profile/following/update/$', nc_views.SignupUserFollowingUpdateView.as_view(), name='account-signup-following-update'),
    url(r'^accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nc/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime, dateutil.parser, parse, requests, stream, sys

from allauth.account.adapter import get_adapter
from allauth.account import views as allauth_account_views
from allauth.utils import build_absolute_uri

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import (
    Avg, BooleanField, Case, ExpressionWrapper, F, FloatField,
    prefetch_related_objects, Value, When,
)
from django.db.models.functions import Lower, Trunc
from django.http import (
    Http404, HttpResponse, HttpResponseNotFound, HttpResponseRedirect,
)
from django.http.request import QueryDict
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from functools import partial

from stellar_base.address import Address
from stellar_base.asset import Asset as StellarAsset
from stellar_base.operation import Operation
from stellar_base.stellarxdr import Xdr
from stellar_base.utils import AccountNotExistError

from stream_django.client import stream_client
from stream_django.feed_manager import feed_manager

from urlparse import urlparse

from . import forms, mixins
from .models import (
    Account, AccountFundRequest, Asset, FollowRequest, Portfolio,
    portfolio_data_collector, Profile, RawPortfolioData,
)


# Web app views
# Landing page
class HomeView(generic.TemplateView):
    """
    Queryset is users sorted by performance rank.
    Prefetch assets_trusting to also preview portfolio assets with each list item.
    """
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        """
        Update context with top 5 performing users and top 5 Stellar assets.
        """
        context = super(HomeView, self).get_context_data(**kwargs)

        # Only fetch top 5 users
        context['allowed_portfolio_displays'] = [ 'usd_value', 'performance_1d' ]
        context['portfolio_display'] = 'performance_1d'
        context['user_list'] = get_user_model().objects\
            .exclude(profile__portfolio__rank=None)\
            .filter(profile__portfolio__rank__lte=5)\
            .prefetch_related('assets_trusting', 'profile__portfolio')\
            .order_by('profile__portfolio__rank')

        # Only fetch top 5 assets
        context['allowed_asset_displays'] = [ 'activityScore', 'price_USD',
            'change24h_USD' ]
        context['asset_display'] = 'price_USD'

        # Fetch the StellarTerm ticker json and store
        r = requests.get(settings.STELLARTERM_TICKER_URL)
        json = r.json()
        ticker_assets = json.get('assets', [])

        # NOTE: Need to get USD/XLM 24 hour change from _meta key (not in XLM-native asset)
        xlm_change24h_USD = None
        if '_meta' in json and 'externalPrices' in json['_meta']\
        and 'USD_XLM_change' in json['_meta']['externalPrices']:
            xlm_change24h_USD = json['_meta']['externalPrices']['USD_XLM_change']

        # Clean the ticker assets to only include those that have
        # the display attribute
        cleaned_ticker_assets = [
            a for a in ticker_assets
            if a['id'] == 'XLM-native' or ('activityScore' in a and a['activityScore'] != None)
        ]

        # Parse to get asset_ids for queryset filter
        top_asset_ids = [ a['id'] for a in cleaned_ticker_assets ]

        # Store the dict version of ticker assets
        ticker_assets = { a['id']: a for a in cleaned_ticker_assets }

        # Order the qset by activityScore
        # TODO: Figure out how to annotate qset properly
        assets = list(Asset.objects.filter(asset_id__in=top_asset_ids))
        for a in assets:
            for display in context['allowed_asset_displays']:
                if a.asset_id == 'XLM-native' and display == 'change24h_USD':
                    # Handling the XLM-native USD % change edge case
                    setattr(a, display, xlm_change24h_USD)
                else:
                    setattr(a, display, ticker_assets[a.asset_id].get(display))
        assets.sort(key=lambda a: getattr(a, 'activityScore'), reverse=True)

        context['asset_list'] = assets[:5]

        return context


## Allauth
class SignupView(mixins.RecaptchaContextMixin, allauth_account_views.SignupView):
    """
    Override so reCAPTCHA is validated.
    """
    form_class = forms.SignupForm

    def get_form_kwargs(self):
        """
        Need to override to pass in the request for authenticated user.
        """
        kwargs = super(SignupView, self).get_form_kwargs()
        kwargs.update({
            'g-recaptcha-response': self.request.POST.get('g-recaptcha-response')
        })
        return kwargs

class PasswordChangeView(allauth_account_views.PasswordChangeView):
    """
    Override so success url redirects to user settings.
    """
    success_url = reverse_lazy('nc:user-settings-redirect')

class SignupStellarUpdateView(LoginRequiredMixin, mixins.AccountFormContextMixin,
    generic.TemplateView):
    template_name = 'account/signup_stellar_update_form.html'
    user_field = 'request.user'

class SignupUserUpdateView(LoginRequiredMixin, mixins.PrefetchedSingleObjectMixin,
    generic.UpdateView):
    model = get_user_model()
    form_class = forms.UserProfileWithPrivacyUpdateMultiForm
    template_name = 'account/signup_profile_update_form.html'
    success_url = reverse_lazy('account-signup-stellar-update')
    prefetch_related_lookups = ['profile']

    def get_object(self, queryset=None):
        """
        Just return the request.user object with prefetched profile.
        """
        if queryset is None:
            queryset = self.get_queryset()

        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj

    def get_form_kwargs(self):
        """
        Need to override to pass in appropriate instances to multiform.

        https://django-betterforms.readthedocs.io/en/latest/multiform.html#working-with-updateview
        """
        kwargs = super(SignupUserUpdateView, self).get_form_kwargs()
        kwargs.update(instance={
            'user': self.object,
            'profile': self.object.profile,
        })
        return kwargs

    def get_queryset(self):
        """
        Authenticated user can only update themselves.
        """
        return self.model.objects.filter(id=self.request.user.id)


class SignupUserFollowingUpdateView(LoginRequiredMixin, generic.ListView):
    template_name = 'account/signup_profile_follow_update_form.html'

    def get_queryset(self):
        """
        Queryset is users sorted by performance rank.
        Prefetch assets_trusting to also preview portfolio assets with each list item.
        """
        # Aggregate the users current user is following and has requested to follow
        # for annotation
        is_following_ids = [
            u.id for u in get_user_model().objects\
                .filter(profile__in=self.request.user.profiles_following.all())
        ]
        requested_to_follow_ids = [
            r.user.id for r in self.request.user.requests_to_follow.all()
        ]

        # Only return top 25 users
        return get_user_model().objects\
            .exclude(profile__portfolio__rank=None)\
            .filter(profile__portfolio__rank__lte=25)\
            .annotate(is_following=Case(
                When(id__in=is_following_ids, then=Value(True)),
                default=Value(False),
                output_field=BooleanField(),
            ))\
            .annotate(requested_to_follow=Case(
                When(id__in=requested_to_follow_ids, then=Value(True)),
                default=Value(False),
                output_field=BooleanField(),
            ))\
            .prefetch_related('assets_trusting', 'profile__portfolio')\
            .order_by('profile__portfolio__rank')


## User
class UserDetailView(mixins.PrefetchedSingleObjectMixin, mixins.IndexContextMixin,
    mixins.LoginRedirectContextMixin, mixins.ActivityFormContextMixin,
    mixins.AccountFormContextMixin, mixins.FeedActivityContextMixin,
    mixins.ViewTypeContextMixin, mixins.DepositAssetsContextMixin,
    mixins.UserAssetsContextMixin, generic.DetailView):
    model = get_user_model()
    slug_field = 'username'
    template_name = 'nc/profile.html'
    prefetch_related_lookups = ['accounts', 'profile__portfolio']
    feed_type = settings.STREAM_USER_FEED
    user_field = 'object'
    view_type = 'profile'

    def get_context_data(self, **kwargs):
        """
        Provide a cryptographically signed username of authenticated user
        for add Stellar account if detail object is current user.
        """
        context = super(UserDetailView, self).get_context_data(**kwargs)
        if self.object:
            # Update the context for follow attrs
            context['followers_count'] = self.object.profile.followers.count()
            context['following_count'] = self.object.profiles_following.count()
            context['is_following'] = self.object.profile.followers\
                .filter(id=self.request.user.id).exists() if self.request.user.is_authenticated else False
            context['requested_to_follow'] = self.object.follower_requests\

nc/templates/nc/feed_news_list.html
{% extends "nc/base.html" %}
{% load static %}
{% load bootstrap %}
{% load humanize %}
{% load nc_extras %}

{% block head %}{% endblock %}

{% block nc_style %}
<link rel="stylesheet" type="text/css" href='{% static 'nc/feed.css' %}' />
{% endblock %}

{% block title %}News | Nucleo{% endblock %}

{% block main %}
<div class="list-group mb-3">
  <div class="list-group-item flex-column align-items-start">
    <a href="{% url 'nc:user-redirect' %}" class="list-group-item list-group-item-action d-flex w-100 justify-content-between p-0 border-0">
      <div class="d-flex flex-row align-items-center my-2">
        <div class="mr-2">
          <img class="img-object-fit-cover img-thumbnail flex-auto" style="height: 70px; width: 70px;"{% if profile and profile.pic %} src="{{ profile.pic.url }}"{% else %} src="{% static 'nc/images/profile.png' %}"{% endif %} alt="">
        </div>
        <div class="d-flex flex-column align-items-start justify-content-start">
          <strong>{{ request.user.get_full_name }}</strong>
          <small class="text-secondary">@{{ request.user.username }}</small>
          <small>
            {% for a in request.user.assets_trusting.all %}
            <img class="img-object-fit-cover rounded-circle" {% if a.name %}title="{{ a.name }}"{% else %}title="{{ a.code }} (Issuer: {{ a.issuer_address|truncatechars:8 }}{{ a.issuer_address|slice:'-5:' }})"{% endif %} style="height: 15px; width: 15px;"{% if a.pic %} src="{{ a.pic.url }}"{% elif a.toml_pic %} src="{{ a.toml_pic }}"{% else %} src="{% static 'nc/images/asset.png' %}"{% endif %} alt="">
            {% endfor %}
          </small>
        </div>
      </div>
    </a>
    <div class="d-flex flex-wrap w-100 justify-content-between align-items-end">
      <div class="d-flex flex-column">
        <div class="btn-group pr-2 my-1">
          {% if profile.portfolio.rank %}
          <a href="{% url 'nc:leaderboard-redirect' %}" title="Leaderboard Ranking (1d)" class="btn btn-sm btn-warning">
            <span data-feather="award"></span>
            {{ profile.portfolio.rank }}
          </a>
          {% endif %}
          <button type="button" title="Your Portfolio Value ({{ portfolio_latest_created|naturaltime }})" class="btn btn-sm btn-dark">
            ${{ portfolio_latest_usd_value|floatformat:2|intcomma }}
          </button>
          {% with profile.portfolio|get_attribute:performance_attr as performance %}
          {% if performance != None %}
          <button type="button" title="Your Portfolio Performance ({{ date_span }})" {% if performance > 0 %}class="btn btn-sm btn-success"{% elif performance < 0 %}class="btn btn-sm btn-danger"{% else %}class="btn btn-sm btn-secondary"{% endif %}>
            {% if performance > 0 %}+{% endif %}{{ performance|percentage }}
          </button>
          {% endif %}
          {% endwith %}
        </div>
      </div>
      <div class="d-flex flex-column">
        <div>
          <button type="button" class="btn btn-sm btn-outline-dark my-1" data-toggle="modal" data-target="#depositFundsModal">
            <span data-feather="download"></span>
            Deposit Funds
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Deposit funds modal -->
<div class="modal fade" id="depositFundsModal" tabindex="-1" role="dialog" aria-labelledby="depositFundsModalTitle" aria-hidden="true">
  <form method="POST" id="depositFundsModalForm">
    {% csrf_token %}
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="depositFundsModalTitle">Deposit Funds To Stellar</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <h5 id="depositFundsModalHeader" class="pt-1 mb-3 modal-body-header">Please select an asset type and a Stellar account to receive deposit</h5>
          <div class="form-group">
            <label for="depositFundsModalAssetSelect">Asset type</label>
            <select class="custom-select" id="depositFundsModalAssetSelect" name="asset" required="">
              <option value="">Choose...</option>
              {% for a in deposit_assets %}
              <option value="{{ a.asset_id }}" data-code="{{ a.code }}" data-issuer="{{ a.issuer_address }}">{{ a.code }}</option>
              {% endfor %}
            </select>
            <div class="invalid-feedback">
              Please select a valid asset.
            </div>
            {% for a in deposit_assets %}
            <div class="deposit-asset d-none py-3" data-asset_id="{{ a.asset_id }}">
              <label class="text-muted">Stellar asset to be deposited</label>
              <div class="d-flex flex-wrap justify-content-start align-items-center border-0">
                <img class="img-object-fit-cover img-thumbnail rounded-circle" style="height: 60px; width: 60px;" src="{{ a.pic_url }}" alt="">
                <div class="ml-2 d-flex flex-column align-items-start justify-content-center">
                  <strong>{{ a.code }}</strong>
                  <span class="text-secondary">{{ a.domain }}</span>
                  <small class="text-muted" style="font-size: 0.6em">Issuer: {{ a.issuer_address }}</small>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          <div class="form-group">
            <label for="depositFundsModalAccountSelect">Stellar account</label>
            <select class="custom-select" id="depositFundsModalAccountSelect" name="account" required="">
              <option value="">Choose...</option>
              {% for acc in request.user.accounts.all %}
              <option value="{{ acc.public_key }}">{% if acc.name %}{{ acc.name }} {% endif %}({{ acc.public_key|truncatechars:10 }}{{ acc.public_key|slice:"-7:" }})</option>
              {% endfor %}
            </select>
            <small><a href="{% url 'nc:user-detail' request.user.username %}#accounts">Add a Stellar account</a></small>
            <div class="invalid-feedback">
              Please select a valid account.
            </div>
          </div>
        </div>
        <div class="modal-body py-0">
          <div class="mb-3 d-inline-flex justify-content-start align-items-center">
            <img class="img-object-fit-cover img-thumbnail rounded flex-auto" style="height: 50px; width: 50px;" src="{% static 'nc/images/papaya.png' %}" alt="">
            <div class="ml-2 d-flex flex-column align-items-start justify-content-center">
              <strong>Powered by Papaya</strong>
              <a href="https://apay.io" target="_blank" class="text-secondary">apay.io</a>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary ladda-button" data-style="expand-left" data-size="s" {% if request.user.accounts.count == 0 %}disabled{% endif %}><span class="ladda-label">Get External Address</span></button>
        </div>
      </div>
    </div>
  </form>
</div>

{% if request.user.follower_requests.count > 0 %}
<div class="card card-requests mb-4">
  <div class="card-header border-0">
    Follower requests
  </div>
  <div class="card-body p-0">
    {% for fr in follower_requests %}
    <div class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'nc:user-detail' fr.requester.username %}" class="list-group-item-action d-inline-flex justify-content-start align-items-center">
        <img class="img-object-fit-cover img-thumbnail flex-auto" style="height: 50px; width: 50px;"{% if fr.requester.profile and fr.requester.profile.pic %} src="{{ fr.requester.profile.pic.url }}"{% else %} src="{% static 'nc/images/profile.png' %}"{% endif %} alt="">
        <div class="ml-2 d-flex flex-column align-items-start justify-content-center">
          <strong>{{ fr.requester.get_full_name }}</strong>
          <small class="text-muted">@{{ fr.requester.username }}</small>
        </div>
      </a>
      <div class="btn-group">
        <form method="POST" action="{% url 'nc:user-follow-request-update' fr.requester.username %}">
          {% csrf_token %}
          <input name="success_url" type="hidden" value="{{ request.get_full_path }}">
          <button type="submit" class="btn btn-sm btn-outline-primary">Confirm</button>
        </form>
        <form method="POST" class="ml-1" action="{% url 'nc:user-follow-request-delete' fr.requester.username %}">
          {% csrf_token %}
          <input name="success_url" type="hidden" value="{{ request.get_full_path }}">
          <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
        </form>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}

<div class="card mb-2">
  <div class="card-body p-0 m-0">
    <ul class="nav nav-pills nav-justified">
      <li class="nav-item">
        <a title="Leaderboard" class="nav-link btn-outline-warning rounded-0 rounded-left" href="{% url 'nc:leaderboard-redirect' %}">
          <span data-feather="award"></span>
        </a>
      </li>
      <li class="nav-item">
        <a title="Trade" class="nav-link btn-outline-success rounded-0" href="{% url 'nc:trade-redirect' %}">
          <span data-feather="trending-up"></span>
        </a>
      </li>
      <li class="nav-item">
        <a title="Feed" class="nav-link btn-outline-info rounded-0 rounded-right active" href="{% url 'nc:feed-redirect' %}">
          <span data-feather="activity"></span>
        </a>
      </li>
    </ul>
  </div>
</div>

<div class="card card-feed">
  <div class="card-header border-0 d-flex flex-wrap justify-content-between align-items-center">
    <div class="mb-1 d-flex flex-column justify-content-between align-items-start">
      <h5>Top Activity From Your Friends</h5>
      <span class="text-secondary">Gain insight into which tokens are making them the most</span>
    </div>
    <div class="btn-group" role="group">
      <a href="{% url 'nc:feed-activity' %}" class="btn btn-sm btn-primary">Activity</a>
      <a href="{% url 'nc:feed-news' %}" class="btn btn-sm btn-primary active">News</a>
    </div>
  </div>
  <div class="card-body p-0">
    <div id="newsList" class="list-group">
      {% for object in object_list %}
      <a href="{{ object.url }}" target="_blank" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h6 class="mb-1">{{ object.title | safe }}</h6>
          <small class="time-since pl-1 text-right" data-created_at="{{ object.created_at }}"></small>
        </div>
        <p class="mb-2 text-muted">{{ object.domain }}</p>
        <small class="d-flex flex-wrap justify-content-start align-items-center">
          {% with object.votes as votes %}
          {% if votes.positive > 0 %}
          <span class="mr-2 text-success">
          <span data-feather="arrow-up"></span>
          {{ votes.positive }}
          </span>
          {% endif %}
          {% if votes.negative > 0 %}
          <span class="mr-2 text-danger">
          <span data-feather="arrow-down"></span>
          {{ votes.negative }}
          </span>
          {% endif %}
          {% if votes.important > 0 %}
          <span class="mr-2 text-warning">
          <span data-feather="alert-triangle"></span>
          {{ votes.important }}
          </span>
          {% endif %}
          {% if votes.liked > 0 %}
          <span class="mr-2">
          <span data-feather="thumbs-up"></span>
          {{ votes.liked }}
          </span>
          {% endif %}
          {% if votes.disliked > 0 %}
          <span class="mr-2">
          <span data-feather="thumbs-down"></span>
          {{ votes.disliked }}
          </span>
          {% endif %}
          {% if votes.saved > 0 %}
          <span class="mr-2">
          <span data-feather="star"></span>
          {{ votes.saved }}
          </span>
          {% endif %}
          {% endwith %}
        </small>
      </a>
      {% endfor %}
    </div>
  </div>
  <div class="card-footer border-0 d-flex justify-content-start align-items-center">
    <button id="moreButton" type="button" class="btn btn-sm btn-link more p-0" data-parent="#newsList" data-url="{{ next }}" {% if next %}data-has_more="true"{% else %}data-has_more="false"{% endif %}>More</button>
  </div>
</div>
{% endblock %}


{% block nc_script %}
<script>
  const PAPAYA_API_DEPOSIT_URL = "{{ papaya_api_deposit_url }}",
        PAPAYA_ASSET_TRUST_LINKS = {
          {% for a in deposit_assets %}
          {{ a.code }}: "{% url 'nc:asset-trust-list' a.asset_id %}",
          {% endfor %}
        };
</script>
<script src="{% static 'nc/scripts/deposit.js' %}"></script>
<script src="{% static 'nc/scripts/feed_news.js' %}"></script>
{% endblock %}

nc/templates/nc/profile_portfolio_data_list.html
{% extends "nc/base.html" %}
{% load static %}
{% load bootstrap %}

{% block head %}{% endblock %}

{% block nc_style %}
{% endblock %}

{% block title %}Historical Portfolio Data | Nucleo{% endblock %}

{% block main %}
{% endblock %}


{% block nc_script %}
{% endblock %}